import { useState } from 'react';
import { suggestOutfit } from '../utils/outfitSuggester';
import { generateAvatarImage } from '../utils/avatarGenerator';
import { RefreshCw, Loader2 } from 'lucide-react';

export function SuggestionView({ items }) {
    const [outfit, setOutfit] = useState(null);
    const [avatarUrl, setAvatarUrl] = useState(null);
    const [isLoading, setIsLoading] = useState(false);
    const [loadingStatus, setLoadingStatus] = useState('');
    const [error, setError] = useState(null);

    const handleSuggest = async () => {
        setIsLoading(true);
        setError(null);
        setOutfit(null);
        setAvatarUrl(null);
        
        try {
            // 1. Get Suggestion from HF LLM
            setLoadingStatus('AI Stylist is analyzing your wardrobe...');
            const suggestionResult = await suggestOutfit(items);
            
            if (suggestionResult.error) {
                setError(suggestionResult.error);
                setIsLoading(false);
                return;
            }
            
            setOutfit(suggestionResult);

            // 2. Generate Avatar from Hugging Face
            setLoadingStatus('Drawing your custom avatar...');
            const avatarResult = await generateAvatarImage(suggestionResult);
            
            if (avatarResult.error) {
                // We still show the outfit even if the avatar fails
                setError(avatarResult.error);
            } else {
                setAvatarUrl(avatarResult.imageUrl);
            }

        } catch (err) {
            console.error(err);
            setError("Something went wrong during generation.");
        } finally {
            setIsLoading(false);
            setLoadingStatus('');
        }
    };

    return (
        <div className="container" style={{ paddingBottom: '100px' }}>
            <div className="app-header">
                <h1 className="editorial-title app-title">Today's Fit</h1>
                <p className="app-subtitle">AI-Powered Styling</p>
            </div>

            <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
                <button 
                    className="btn-primary" 
                    onClick={handleSuggest} 
                    disabled={isLoading}
                    style={{ padding: '0.75rem 2rem', fontSize: '1.1rem', opacity: isLoading ? 0.7 : 1 }}
                >
                    {isLoading ? <Loader2 size={18} className="spin" style={{ animation: 'spin 2s linear infinite' }} /> : <RefreshCw size={18} />} 
                    {isLoading ? ' Generating...' : ' Get AI Suggestion'}
                </button>
                {loadingStatus && (
                    <div style={{ marginTop: '1rem', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                        {loadingStatus}
                    </div>
                )}
            </div>

            {error && (
                <div className="card" style={{ textAlign: 'center', color: 'var(--error-color)', padding: '1rem', marginBottom: '2rem', border: '1px solid var(--error-color)' }}>
                    {error}
                </div>
            )}

            {outfit && (
                <div>
                    {/* Stylist Reasoning */}
                    {outfit.reasoning && (
                        <div className="card" style={{ marginBottom: '2rem', backgroundColor: 'var(--brand-color)', color: 'white' }}>
                            <p style={{ fontStyle: 'italic', fontSize: '0.95rem', lineHeight: 1.6 }}>
                                "{outfit.reasoning}"
                            </p>
                            <div style={{ fontSize: '0.75rem', marginTop: '0.5rem', opacity: 0.8 }}>— AI Stylist</div>
                        </div>
                    )}

                    {/* Avatar Display */}
                    <div className="avatar-container">
                        <div className="avatar-figure" style={{ backgroundColor: '#f0f0f0', backgroundImage: avatarUrl ? `url(${avatarUrl})` : 'none', backgroundSize: 'cover', backgroundPosition: 'center', border: 'none' }}>
                            {!avatarUrl && !isLoading && (
                                <div style={{ height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#999', padding: '2rem', textAlign: 'center' }}>
                                    Avatar will appear here
                                </div>
                            )}
                        </div>
                        <p style={{ marginTop: '1rem', color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
                            Generated by Hugging Face FLUX
                        </p>
                    </div>

                    {/* Breakdown */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem', borderBottom: '1px solid var(--accent-color)', paddingBottom: '0.5rem' }}>Outfit Breakdown</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                            {['top', 'bottom', 'shoe', 'jacket', 'belt'].map(part => {
                                const item = outfit[part];
                                if (!item) return null;
                                return (
                                    <div key={part} style={{ display: 'flex', alignItems: 'center' }}>
                                        <div style={{ width: '50px', height: '50px', backgroundColor: 'var(--accent-color)', borderRadius: '4px', marginRight: '1rem', overflow: 'hidden' }}>
                                            {item.image && <img src={item.image} alt="" style={{width:'100%', height:'100%', objectFit:'cover'}} />}
                                        </div>
                                        <div>
                                            <div style={{ textTransform: 'uppercase', fontSize: '0.7rem', color: 'var(--text-secondary)', letterSpacing: '0.05em' }}>
                                                {part}
                                            </div>
                                            <div style={{ fontWeight: 500 }}>{item.color} {item.category}</div>
                                            <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                                                {item.pattern} • {item.material}
                                            </div>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
